---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  # environment:
  # Add more env vars here
  tasks:
    - name: "Test"
      become: yes
      shell: git --version

    - name: "change directory"
      become: yes
      shell: cd /home/ubuntu/realxchangerate.web & cat docker-compose.yml

    - name: "Stop docker"
      become: yes
      shell: /home/ubuntu/realxchangerate.web/docker-compose down

    - name: "Start docker"
      become: yes
      shell: /home/ubuntu/realxchangerate.web docker-compose up -d

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
